### ISSUE TITLE
memset overflow!!!

### ISSUE THREAD

**Issue by fernicmarotta** [MDK-Packs/IoT_Socket#10]
https://github.com/MDK-Packs/IoT_Socket/blob/69af5e7a0affd8e06b0b68a2dfa0ba116d8606a9/source/mdk_network/iot_socket.c#L135

In order to avoid memset internal struct array, take in count backlog Socket: 
![image](https://github.com/user-attachments/assets/964170f7-d4df-4ba8-aecf-a0fff9ad9f64)
Since only BSD_NUM_SOCKS is not enough, the number of the descriptor can be larger and set memory of other contiguous element.
![image](https://github.com/user-attachments/assets/2f98c212-ee91-4e7a-8adf-0f12438cbdfc)
this behavior can be reproduced if the user take BSD_NUM_SOCKS and BSD_SERVER_SOCKS a listening socket, and 1 create listen and socket  then BSD_NUM_SOCKS client socket

**Comment by furbanc** [comment]
Yes, that is a bug. Thank you for pointing it out. It will be corrected soon.

**Comment by RobertRostohar** [comment]
Should be fixed with commit 1a02ab8.

**Comment by fernicmarotta** [comment]
thank you

**Comment by fernicmarotta** [comment]
upload new pack version please, V1.3.1?

**Comment by RobertRostohar** [comment]
A newer version 1.4.0 with also other features is planned to be released in the next few days.

**Comment by RobertRostohar** [comment]
Version 1.4.0 has been released.
