### ISSUE TITLE
Missing type specification from iotSocketGetOpt and iotSocketSetOpt

### ISSUE THREAD

**Issue by paul-szczepanek-arm** [MDK-Packs/IoT_Socket#8]
Options should have platform specific independent type and size (like uint32_t) that is checked against. Right now the implementations pass through the type instead of translating between implementation and API. This means the user needs to know the implementation detail instead of relying on the API.
See: https://github.com/MDK-Packs/IoT_Socket/pull/7

I propose we list all options with corresponding sizes in the doxygen block of the function.

**Comment by RobertRostohar** [comment]
Type specification has been added to the documentation as requested.

**Comment by RobertRostohar** [comment]
Closing due to being fixed and no further feedback.
